flowchart TB
    dcf-main_app([UI]):::nodeClass
    dcf-main_app_mobile_optimized([UI]):::nodeClass
    dcf-main_bridge_adapter[[Engine]]:::nodeClass
    dcf-main_capm([UI]):::nodeClass
    dcf-main_connectors_aws_min[[Engine]]:::nodeClass
    dcf-main_damodaran([UI]):::nodeClass
    dcf-main_data_gatekeeper[[Data]]:::nodeClass
    dcf-main_db___init__[[Mod]]:::nodeClass
    dcf-main_db_engine[[Engine]]:::nodeClass
    dcf-main_db_models[[Engine]]:::nodeClass
    dcf-main_dcf_valuation([UI]):::nodeClass
    dcf-main_debug_airnz[[Data]]:::nodeClass
    dcf-main_ev_ebitda[[Engine]]:::nodeClass
    dcf-main_excel_bridge[[Engine]]:::nodeClass
    dcf-main_fama_french([UI]):::nodeClass
    dcf-main_fcf_calculations([UI]):::nodeClass
    dcf-main_fcfe[[Engine]]:::nodeClass
    dcf-main_fetch_damodaran_betas([UI]):::nodeClass
    dcf-main_fin_report_tab([UI]):::nodeClass
    dcf-main_fin_stat_downloader([UI]):::nodeClass
    dcf-main_finance_data_loader[[Data]]:::nodeClass
    dcf-main_generate_report[[Engine]]:::nodeClass
    dcf-main_hedge_prompt[[Engine]]:::nodeClass
    dcf-main_historical_data_extractor[[Data]]:::nodeClass
    dcf-main_metrics[[Engine]]:::nodeClass
    dcf-main_news_fetcher[[Engine]]:::nodeClass
    dcf-main_nwc[[Engine]]:::nodeClass
    dcf-main_ocr_image_pdf[[Mod]]:::nodeClass
    dcf-main_pdf_text[[Mod]]:::nodeClass
    dcf-main_project_description_tab([UI]):::nodeClass
    dcf-main_qa_engine_QnA([UI]):::nodeClass
    dcf-main_qa_tab([UI]):::nodeClass
    dcf-main_regression_engine[[Engine]]:::nodeClass
    dcf-main_risk_hedge[[Data]]:::nodeClass
    dcf-main_scrape_damodaran[[Engine]]:::nodeClass
    dcf-main_scrape_ff5([UI]):::nodeClass
    dcf-main_stock_analysis_renderer([UI]):::nodeClass
    dcf-main_stock_returns([UI]):::nodeClass
    dcf-main_test_bridge[[Engine]]:::nodeClass
    dcf-main_ticker_to_industry[[Mod]]:::nodeClass
    dcf-main_ticker_to_region[[Mod]]:::nodeClass
    dcf-main_video_transcribe[[Mod]]:::nodeClass
    dcf-main_wacc_engine[[Engine]]:::nodeClass
    dcf-main_web_scraper[[Mod]]:::nodeClass
    dcf-main_db_engine --> dcf-main_db_models